name: Sed-replacer
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Lycihararobot"
          replace: "Lyci"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Welcome To Lyci'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: ğ™‹ğ™§ğ™–ğ™—ğ™ğ™–ğ™¨ğ™ğ™– â€¢â€¢â€¢
          commit_user_email: prabhasha999@gmail.com
          commit_author: ğ™‹ğ™§ğ™–ğ™—ğ™ğ™–ğ™¨ğ™ğ™– â€¢â€¢â€¢ <prabhasha999@gmail.com>
